parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.05 --seed {1} ::: 1 2
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.05 --seed {1} ::: 3 4
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.05 --seed {1} ::: 5 6
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.05 --seed {1} ::: 7 8
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.05 --seed {1} ::: 9 10
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.1 --seed {1} ::: 1 2
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.1 --seed {1} ::: 3 4
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.1 --seed {1} ::: 5 6
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.1 --seed {1} ::: 7 8
parallel -j 2 python train.py --swanlab --decouple --train_step 200 --loop_nums 10  --adv_steps 6 --cuda_number 1 --adv_test  --attack_eps 0.1 --seed {1} ::: 9 10